### PR TITLE
Added Status Board to adopters list

### PR DESCRIPTION
**Pull request by jameswlane**

### CODE REVIEW

**Comment by CloudNativeJSDevOps** [comment]
Hi James. 

This is awesome, thanks. In terms of the LTS timeline for Status Board, the only entry you should need at the moment is:

| Module Version   | Release Date | Minimum EOL | EOL With     | Status  |
|------------------|--------------|-------------|--------------|---------|
| 1.x.x	           | Nov 2017     | Dec 2019    |                      | Current |

As 1.x is the current release, that needs to be marked as Current or LTS for at least the lifetime of the most recent LTS version on Node.js - ie, Node.js 8 until Dec 2019.

If Status Board is still in version 1.x.x once Node.js 10 goes into LTS in October, then the Minimum EOL date would change to April 2021 (the EOL date for Node.js 10).

Does that make sense?

**Comment by seabaylea** [comment]
Hi James. 

This is awesome, thanks. In terms of the LTS timeline for Status Board, the only entry you should need at the moment is:

| Module Version   | Release Date | Minimum EOL | EOL With     | Status  |
|------------------|--------------|-------------|--------------|---------|
| 1.x.x	           | Nov 2017     | Dec 2019    |                      | Current |

As 1.x is the current release, that needs to be marked as Current or LTS for at least the lifetime of the most recent LTS version on Node.js - ie, Node.js 8 until Dec 2019.

If Status Board is still in version 1.x.x once Node.js 10 goes into LTS in October, then the Minimum EOL date would change to April 2021 (the EOL date for Node.js 10).

Does that make sense?

**Comment by jameswlane** [comment]
@seabaylea It makes sense, and I updated the README.md based on you suggestions.

**Comment by seabaylea** [comment]
Hi @jameswlane. Thanks for the update.

Technically your "Current" release should have a minimum EOL with Node.js 8.x (as the latest current LTS version of Node.js), and therefore a date of December 2019.

If your happy to update that, I'll get this merged and socialise that Status Board has adopted LTS via Twitter/Blog, etc.

**Comment by jameswlane** [comment]
@seabaylea I plan on maintaining only a single version of Status Board, due to that I was planning a 2.0 release when 6.x.x reaches EOL and a 3.0 release when 8 reached EOL.

**Comment by seabaylea** [comment]
Hi @jameswlane. The value of providing LTS is so that users don't have to immediately adopt a new major version when it becomes available - they can wait until the point that they have to do a migration anyway (when they have to update Node.js itself).

Under the releases and timeline that I think you're suggesting, you'd have the following release dates:

| Module Version   | Release Date | EOL |
|------------------|--------------|-------------|
| 1.x.x	                | Nov 2017     | April 2019       | 
| 2.x.x                      | April 2019   | Dec 2019      | 
| 3.x.x                      | Dec 2019    |                       | 

The challenge here for users is that there's no overlap - if they are using v1.x, in April 2019 they will have to switch to v2.x. Whilst for users of Node.js 8 that will align with them having to migrate anyway, that won't be true of users of Node.js 10.

**Pull request closed without merging**
